Traceback (most recent call last):
  File "main.py", line 96, in <module>
    size=(240, 240))
  File "main.py", line 9, in __init__
    self.initialize_ui()
  File "main.py", line 13, in initialize_ui
    self.panel = wx.Panel()
  File "c:\Python27x86\lib\site-packages\wx-3.0-msw\wx\_windows.py", line 68, in __init__
    _windows_.Panel_swiginit(self,_windows_.new_Panel(*args, **kwargs))
TypeError: Required argument 'parent' (pos 1) not found
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    size=(240, 240))
  File "main.py", line 9, in __init__
    self.initialize_ui()
  File "main.py", line 13, in initialize_ui
    self.panel = wx.Panel(None)
  File "c:\Python27x86\lib\site-packages\wx-3.0-msw\wx\_windows.py", line 68, in __init__
    _windows_.Panel_swiginit(self,_windows_.new_Panel(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "parent" failed at ..\..\src\msw\window.cpp(521) in wxWindow::Create(): can't create wxWindow without parent
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\Thomas\Desktop\pybean\main.py", line 95, in run
    next_button.click()
  File "C:\Python27x86\lib\site-packages\selenium\webdriver\remote\webelement.py", line 60, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27x86\lib\site-packages\selenium\webdriver\remote\webelement.py", line 370, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "C:\Python27x86\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: u'unknown error: Element is not clickable at point (1291, 113). Other element would receive the click: <div class="ext-el-mask" id="ext-gen36" style="display: block; width: 1920px; height: 1395px; z-index: 9000;"></div>\n  (Session info: chrome=39.0.2171.99)\n  (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.3 x86_64)' 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "main.py", line 91, in run
    proceed = self.browser.find_element_by_id("Proceed")
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: u'no such element\n  (Session info: chrome=39.0.2171.99)\n  (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.3 x86_64)' 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "main.py", line 88, in run
    start = self.browser.find_element_by_id("start-button")
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: u'no such element\n  (Session info: chrome=39.0.2171.99)\n  (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.3 x86_64)' 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "main.py", line 98, in run
    next_button.click()
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webelement.py", line 60, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webelement.py", line 370, in _execute
    return self._parent.execute(command, params)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "c:\Python27x86\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: u'unknown error: Element is not clickable at point (1291, 113). Other element would receive the click: <div class="ext-el-mask" id="ext-gen23" style="display: block; width: 1920px; height: 1395px; z-index: 9000;"></div>\n  (Session info: chrome=39.0.2171.99)\n  (Driver info: chromedriver=2.12.301325 (962dea43ddd90e7e4224a03fa3c36a421281abb7),platform=Windows NT 6.3 x86_64)' 

